[pytest]
pythonpath = .
# Base directory for relative paths
testpaths = ui api  # Directories to discover tests

# Specify markers for categorizing tests
markers =
    ui: Marks UI tests
    api: Marks API tests
    smoke: Marks smoke tests
    regression: Marks regression tests
    login: Marks login-related tests
    cleanup: Marks API tests to run after UI tests

# Customizing output verbosity
addopts = -v --tb=short --capture=no --maxfail=3

log_cli = true
log_cli_level = INFO
log_file_level = DEBUG
log_format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_file = logs/general_log.log